# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Force Chromium-based browsers (Chrome, Brave, Edge, etc.) to use Wayland native scaling
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = CHROMIUM_OZONE_PLATFORM_HINT,auto
