general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch 'hl.dsp.dpms({state = "on"})' && hyprctl reload  # delay for PAM readiness, turn on display, reload as a safety net for the touchpad-reset resume fix
    inhibit_sleep = 3                                      # wait until screen is locked
}

listener {
    timeout = 150                                             # 2.5min
    on-timeout = pidof hyprlock || omarchy-launch-screensaver # start screensaver (if we haven't locked already)
}

listener {
    timeout = 151                      # 5min
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({state = "off"})'                   # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({state = "on"})' && brightnessctl -r # screen on when activity is detected
}
