# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
     gaps_in = 0
     gaps_out = 0
     border_size = 1

    # Use master layout instead of dwindle
    # layout = master
}

cursor {
    # Enable cursor warping when focus changes
    no_warps = false
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = no
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# Remove transparency
windowrule = match:class .*, opacity 1.0 1.0

# No border when only one window on the workspace
windowrule = match:class .*, border_size 0, match:workspace w[1]

# Remove forced tile rule for Chrome (conflicts with hy3)
# windowrule = match:tag chromium-based-browser, tile on, unset

# LSFG Overlay
windowrule {
    name = lsfg-overlay
    match:class = lsfg-overlay
    float = on
    center = on
    size = 900 700
    animation = slide
    opacity = 0.95
}

# Enable VRR (Variable Refresh Rate) - Only in fullscreen
# 0 = off, 1 = always, 2 = fullscreen only
misc {
    vrr = 2
    # focus_on_activate = false
}
